# Generated by Django 3.2.21 on 2024-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageUrl',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
    ]
