# Generated by Django 3.2.21 on 2024-03-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_post_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
