# Generated by Django 3.2.21 on 2024-03-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pgn', models.TextField()),
            ],
        ),
    ]
