# Generated by Django 3.2.21 on 2024-03-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_post1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
