# Generated by Django 5.0.6 on 2025-02-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_auto_20240607_2203"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("username", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LatinWords",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("excercise_id", models.IntegerField(unique=True)),
                ("words", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PersonalChessGame",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("pgn", models.TextField()),
            ],
        ),
    ]
